### ISSUE TITLE
msckf-vio.jpg的图是用什么软件画的？ 

### ISSUE THREAD

**Issue by jyzhong** [TurtleZhong/msckf_mono#1]
@ @TurtleZhong

**Comment by TurtleZhong** [comment]
应该是用xmind？具体我可能也记不清楚了


 
---原始邮件---
发件人: "jyzhong"<notifications@github.com>
发送时间: 2019年5月6日(星期一) 中午11:51
收件人: "TurtleZhong/msckf_mono"<msckf_mono@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"Xinliang Zhong"<xinliangzhong@foxmail.com>;
主题: [TurtleZhong/msckf_mono] msckf-vio.jpg的图是用什么软件画的？  (#1)



@ @TurtleZhong

**Comment by jyzhong** [comment]
> 应该是用xmind？具体我可能也记不清楚了
> […](#)
> ---原始邮件--- 发件人: "jyzhong"<notifications@github.com> 发送时间: 2019年5月6日(星期一) 中午11:51 收件人: "TurtleZhong/msckf_mono"<msckf_mono@noreply.github.com>; 抄送: "Mention"<mention@noreply.github.com>;"Xinliang Zhong"<xinliangzhong@foxmail.com>; 主题: [TurtleZhong/msckf_mono] msckf-vio.jpg的图是用什么软件画的？ (#1) @ @TurtleZhong — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

谢谢，正在拜读，如有疑问会和你交流，希望不吝赐教！
